= Connections
:imagesdir: ../assets/images

:description: Learn how to define connections to the orchestrator in OpenNMS Velocloud plugin, to monitor and collect events and performance metrics of Velocloud entities.

First, we have to define the connections the plugin uses to connect to the orchestrator.
A connection consists of an orchestrator URL, an API key to authenticate against the orchestrator, and an alias used to reference it.
Connections are saved internally in the Secure Credentials Vault.

You can use Karaf shell commands and REST endpoints to add, validate, and modify connections.

NOTE: By default, the plugin will validate new connections before saving them.
Use the `force` query parameter to override this behavior.


== Karaf
.Connect to Karaf shell.
[source, console]
----
ssh -p 8101 admin@localhost
----
[source, console]
.List existing connections.
----
admin@opennms()> opennms-velocloud:connection-list --help
DESCRIPTION
        opennms-velocloud:connection-list

        List existing connections

SYNTAX
        opennms-velocloud:connection-list

DETAILS
        List all existing connections to orchestrators
----

[source, console]
.Add a connection.
----
admin@opennms()> opennms-velocloud:connection-add --help
DESCRIPTION
        opennms-velocloud:connection-add

        Add a connection

SYNTAX
        opennms-velocloud:connection-add [options] alias url apiKey

ARGUMENTS
        alias
                Alias
                (required)
        url
                Orchestrator Url
                (required)
        apiKey
                Orchestrator API Key
                (required)

OPTIONS
        -t, --test
                Dry run mode, test the credentials but do not save them
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is

DETAILS
        Add a connection to a velocloud orchestrator
----

[source, console]
.Edit an existing connection.
----
admin@opennms()> opennms-velocloud:connection-edit --help
DESCRIPTION
        opennms-velocloud:connection-edit

	Edit a connection

SYNTAX
        opennms-velocloud:connection-edit [options] alias url apiKey

ARGUMENTS
        alias
                Alias
                (required)
        url
                Orchestrator Url
                (required)
        apiKey
                Orchestrator API Key
                (required)

OPTIONS
        --help
                Display this help message
        -f, --force
                Skip validation and save the connection as-is

DETAILS
        Edit an existing connection to a velocloud orchestrator
----

[source, console]
.Validate an existing connection.
----
admin@opennms()> opennms-velocloud:connection-validate --help
DESCRIPTION
        opennms-velocloud:connection-validate

        Validate a connection

SYNTAX
        opennms-velocloud:connection-validate alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Validate an existing connection to a velocloud orchestrator
----

[source, console]
.Delete an existing connection.
----
admin@opennms()> opennms-velocloud:connection-delete --help
DESCRIPTION
        opennms-velocloud:connection-delete

        Delete a connection

SYNTAX
        opennms-velocloud:connection-delete alias

ARGUMENTS
        alias
                Alias
                (required)

DETAILS
        Deletes a connection to a velocloud orchestrator
----

== REST

See the reference section for information on the xref:reference:endpoints.adoc[REST endpoints].

== Examples

The following example adds a connection with the alias `theAlias` and assumes that the Orchestrator is reachable by the URL `\https://my.velocloud.orchestrator.net` and the API-key is `tHiSiS.TheAP1Key`.

[source, shell]
----
admin@opennms()> opennms-velocloud:connection-add theAlias https://my.velocloud.orchestrator.net/ tHiSiS.TheAP1Key
----

NOTE: If the connection represents a partner connection, you can list the associated customers by invoking `opennms-velocloud:list-customers aPartnerAlias`.
