= Requisitions
:imagesdir: ../assets/images

In order to monitor the Velocloud gateways, edges, and links, you need to import these entities into OpenNMS.
To do so, create a requisition for a given connection alias.
A connection alias can represent a customer connection or a partner connection.
While a customer connection only allows you to query for entities associated with the customer itself, a partner connection has access to top-level entities that are shared by customers.
Furthermore, a partner connection can also be used to import customer entities by providing the customer's `enterpriseId` as an additional parameter.

Specify the requisition type `velocloud-customer` to import all entities of a customer connection:

```
opennms:import-requisition velocloud-customer alias=aCustomerAlias
```

Specify the requisition type `velocloud-partner` to import all entities of a partner connection:

```
opennms:import-requisition velocloud-partner alias=aPartnerAlias
```

A customer requisition can be created using a partner connection alias by providing the `enterpriseId` as an additional parameter.
The following example demonstrates the creation of a customer requisition by using a partner alias and an additional ´enterpriseId` parameter with the value set to `123`.

```
opennms:import-requisition velocloud-customer alias=aPartnerAlias,enterpriseId=123
```

You can specify an additional parameter, `foreignSource`, to set the foreign source and requisition name.
The following example will create a customer requisition named `My-Customer-Requisition`.

```
opennms:import-requisition velocloud-customer alias=aCustomerAlias foreignSource=My-Customer-Requisition
```
