= Terminology
:imagesdir: ../assets/images

This section introduce some of the basic terms we use in this documentation.

Partner:: A *Partner* is a buisness entity that resells Velocloud as a solution.

Customer:: A *Customer* is a customer of a *Partner*.

Orchestrator:: The Velocloud's SD-WAN controller, that hosts REST APIs, including endpoints to retrieve inventory, events, fault data, and performance data. It is used to manage *Gateways*, *Edges* and *Links*.

Gateway:: *Gateways* are the key components of the Velocloud multi-tenant, scalable and redundant network and are deployed in cloud data-centers around the world. These network devices periodically send heartbeat packets and performance metrics to the *Orchestrator*.

Edge:: An *Edge* is a branded physical device that provide secure connectivity to private, public or hybrid applications for a branch site. *Edges* are connected by *Links* to the *Gateways*.

Link:: *Links* are tunnels from an *Edge* device to a *Gateway* providing connectivity to the SD-WAN overlay network.

Hub:: A regional data center that is owned and maintained by a *Customer*.